
export default new Map([
["src/content/proyectos/adventours-Mex.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fadventours-Mex.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/app-healthcheck-smartwatch.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fapp-healthcheck-smartwatch.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/arquitectura-ux-healthcheck.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Farquitectura-ux-healthcheck.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/bit-tournament-2023.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fbit-tournament-2023.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/cv-minimalista.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fcv-minimalista.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/desarrollo-sistema-gestion-actividades.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fdesarrollo-sistema-gestion-actividades.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/diseno-sistema-gestion-actividades.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fdiseno-sistema-gestion-actividades.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/hospital-angel-del-mar.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fhospital-angel-del-mar.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/portafolio-braquetes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fportafolio-braquetes.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/rediseño-app-healthcheck.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fredise%C3%B1o-app-healthcheck.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/seguridad-privada-betaj.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fseguridad-privada-betaj.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/sicroa.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fsicroa.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/sistema-boletos-solteca.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fsistema-boletos-solteca.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/spotify-clone.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fspotify-clone.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/taaniilaaz-muneco-chocolate.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Ftaaniilaaz-muneco-chocolate.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/user-story-mapping-bit-tournament.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fuser-story-mapping-bit-tournament.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/utvco-gestion-cultural-deportiva.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Futvco-gestion-cultural-deportiva.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/vg-design-ui-kit.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fvg-design-ui-kit.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/vgg-movies-search.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fvgg-movies-search.mdx&astroContentModuleFlag=true")],
["src/content/proyectos/vicwithgg-portfolio.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fproyectos%2Fvicwithgg-portfolio.mdx&astroContentModuleFlag=true")]]);
		